version: '3.1'
services:
  nginx:
    container_name: nginx-angular
    image: nginx-angular
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - nest
    networks:
      - na-network

  nest:
    container_name: nest-server
    image: nest-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks:
      - na-network

networks:
  na-network:
    driver: bridge
