version: '3.1'
services:
  nginx:
    container_name: nginx-angular
    image: nginx-angular
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - nest
    networks:
      - na-network

  nest:
    container_name: nest-server
    image: nest-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - na-network

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - "8080:8080"
    networks:
    - na-network

networks:
  na-network:
    driver: bridge
