---
apiVersion: v1
kind: Service
metadata:
  name: dfgna-a
spec:
  selector:
    app: dfgna
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 4200
    targetPort: 4200
  type: LoadBalancer

...