name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/client
          file: ${{ github.workspace }}/client/Dockerfile
          # Add meaningful labels
          labels: |
            maintainer=${{ github.repository_owner }}
            version=${{ github.sha }}
            description=dfg-na client Docker image
          # Set tags for the image (adjust your repo/image name)
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/dfg-na-client:latest
          # Optionally, add more tags for versioning
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dfg-na-client:latest,${{ secrets.DOCKERHUB_USERNAME }}/dfg-na-client:${{ github.sha }}
          # Support multi-platform builds if needed
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          # Enable build cache for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Increase shared memory size if needed
          shm-size: 1g

      # Optionally, add a step to logout from DockerHub
      - name: Log out from DockerHub
        run: docker logout
